# Generated by Django 3.0.8 on 2020-07-28 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mikroblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='micropost',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='micropost',
            name='tag',
            field=models.ManyToManyField(to='tag.Tag'),
        ),
    ]
