# Generated by Django 3.0.8 on 2020-07-31 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mikroblog', '0002_auto_20200728_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micropost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micro_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
