# Generated by Django 3.0.8 on 2020-08-11 17:51

from django.db import migrations, models
import mikroblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('mikroblog', '0007_auto_20200811_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micropost',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=mikroblog.models.upload_location),
        ),
    ]
