# Generated by Django 3.0.8 on 2020-09-01 15:01

import ckeditor.fields
from django.db import migrations, models
import mikroblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('mikroblog', '0007_auto_20200811_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micropost',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='micropost',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=mikroblog.models.upload_location),
        ),
    ]
