# Generated by Django 3.0.8 on 2020-09-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikroblog', '0008_auto_20200901_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micropost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
