# Generated by Django 3.0.8 on 2020-08-07 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200731_1230'),
        ('likes', '0002_auto_20200731_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='micro_post_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='micro_post_reactions', to='comment.Comment'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='post_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to='comment.Comment'),
        ),
    ]
