# Generated by Django 3.0.8 on 2020-07-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Kobieta'), (1, 'Mężczyza'), (2, 'Niwuadu')]),
        ),
    ]
