# Generated by Django 3.0.8 on 2020-07-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Kobieta'), (1, 'Kężczyna'), (2, 'Nie chcę podawać swojej płci')]),
        ),
    ]
