# Generated by Django 3.0.8 on 2020-07-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200714_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('k', 'Kobieta'), ('m', 'Kężczyna'), ('n', 'Nie chcę podawać swojej płci')], max_length=1),
        ),
    ]
