# Generated by Django 3.0.8 on 2020-07-14 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200714_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_image',
            new_name='avatar',
        ),
    ]
