# Generated by Django 3.0.8 on 2020-07-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200722_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
