# Generated by Django 3.0.8 on 2020-07-24 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activity',
        ),
    ]
