# Generated by Django 3.0.8 on 2020-09-05 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0001_initial'),
        ('blog', '0009_auto_20200903_1401'),
        ('mikroblog', '0009_auto_20200903_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sub', 'Sub'), ('block', 'Block')], max_length=5)),
                ('micro_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_micro_posts', to='mikroblog.MicroPost')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_posts', to='blog.Post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tag.Tag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
