# Generated by Django 3.0.8 on 2020-09-05 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200903_1401'),
        ('mikroblog', '0009_auto_20200903_1401'),
        ('tag', '0001_initial'),
        ('subscribe', '0002_subscribe_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='micro_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_micro_posts', to='mikroblog.MicroPost'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourite_posts', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tag.Tag'),
        ),
    ]
