# Generated by Django 3.1.1 on 2020-09-12 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('subscribe', '0003_auto_20200905_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_subscriptions', to='tag.tag'),
        ),
    ]
