# Generated by Django 3.0.8 on 2020-07-24 18:23

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='user.png', upload_to=blog.models.upload_location),
        ),
    ]
