# Generated by Django 3.0.8 on 2020-08-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200810_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
