# Generated by Django 3.0.8 on 2020-08-08 10:03

import comment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20200807_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=comment.models.upload_location),
        ),
    ]
